# Lista de ejercicios 3

1.Definimos:
```
x <- c(5, 2, 1, 4)
y <- rep(1, 5)
```
Predice las soluciones antes de escribir los comandos:

(a)

- `sum(x)` 

La salida sería **12**, es decir, la suma de los elementos del `vector x`.

- `range(x)` 

La salida sería el vector **(1, 5)** donde sus elementos son el menor y el mayor elemento del `vector x`.

- `sum(y)` 

La salida sería **5**, esto es la suma de los elementos del `vector y`.

- `length(y)` 

La salida sería **5**, esto es la longitud del `vector y`.

- `sum(y)` 

La salida sería **5**, esto es la suma de los elementos del `vector y`.

(b)
- `c(x, y, 13)` 

La salida sería el vector **(5, 2, 1, 4, 1, 1, 1, 1, 1, 13)**. Concatena **x** con **y** con el número **13**.

(c)

- `x[4] * y[2]` 

La salida sería **4**. Esto es el 4to elemento del vector **x** multiplicado por el 2do elemento del vector **y**.

- `x[2:4] + x[1:3]` 

La salida sería el vector **(7, 3, 5)**, es decir, $(x[2]+x[1], x[3]+x[2], x[4]+x[3])$.

(d)

- `x <= 2` 

Evalúa la condición para cada componente del vector **x**. La salida sería **FALSE, TRUE, TRUE, FALSE**.

- `x[x <= 2]` 

Evalúa la condición para cada componente del vector **x** y retorna los elementos que cumplen dicha condición. La salida sería **2, 1**.

- `x[(x != 5) & (x > 3)]` 

Evalúa la condición para cada componente del vector **x** y retorna los elementos que cumplen dicha condición. La salida sería **4**.


(e)

- `rep(1:4,2)` 

La salida sería el vector **(1,2,3,4,1,2,3,4)**. Ya que repite el vector `(1,2,3,4)` dos veces.

- `rep(1:4,each = 2)` 

La salida sería el vector **(1,1,2,2,3,3,4,4)**. Ya que repite 2 veces cada elemento del vector `1:4`.

- `rep(1:4,c(2, 1, 2, 1))` 

La salida sería el vector **(1,1,2,3,3,4)**. Ya que repite cada elemento del primer vector `1:4` la cantidad de veces indicada por cada elemento del segundo vector `c(2, 1, 2, 1)`.

- `rep(1:4,each = 2, len = 10)`

La salida sería el vector **(1,1,2,2,3,3,4,4,1,1)**. Ya que repite 2 veces cada elemento del vector `1:4` hasta que el vector resultante tenga 10 elementos.

(f)

- `2:3^2` 

La salida sería el vector **(2, 3, 4, 5, 6, 7, 8, 9)**. Estos son los números del $2$ al $3^2$, es decir, del $2$ al $9$.

- `seq(2, -3) * c(-1, 1)` 

Multiplica componente a componente. Como el 2do vector es de menor longitud y, además, como la longitud del 1ero es múltiplo del otro, R hace un ***recycling***. La salida sería el vector **(-2, 1, 0, -1, 2, -3)**.

2.

- Describe importantes diferencias entre las estructuras fundamentales de $R$: `vectores`, `matrices`, `arrays` y `listas`. Usa ejemplos para demostrar esas diferencias.

**VECTORES** 

1. El vector es la estructura más básica de datos en R. 
2. Es una concatenación de datos.
3. Todos sus elementos deben ser del mismo tipo. Si tienen diferentes tipos se convierten a uno común (***coerción***).
4. Cada dato recibe un ***índice*** según el orden en el que se concatenó (empezando por 1).
5. Podemos acceder a cada elemento por su ínidce.

In [1]:
message("Coerción: ")
datos <- c('1',2,3,4)
datos

message("Accediendo al segundo elemento del vector: ")
datos[2] 

Coerción: 


[1] "1" "2" "3" "4"

Accediendo al segundo elemento del vector: 


[1] "2"

**ARRAYS**
1. Todos los elementos deben ser del mismo tipo.
2. Tiene un atributo adicional (***dim***) el cual a su vez es un vector numérico de dimensiones (números enteros positivos) formado por varios índices.

In [2]:
mi_array <- array(1:24, dim = c(4,3,2))
mi_array

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24

**MATRICES**
1. Caso particular del array con 2 dimensiones.
2. Tiene un atributo adicional (**dim**) el cual a su vez es un vector numérico de longitud 2, que define el número de filas y columnas de la matriz.
3. Todos sus elementos deben ser del mismo tipo.

In [3]:
mi_matriz <- matrix(1:6,nrow = 3)
mi_matriz

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

**LISTAS**
1. Colección de elementos que pueden ser de diferentes tipos y de diferentes longitudes.
2. Generalmente, los elementos de una lista están identificados por un nombre, siempre que lo tenga.
3. Para obtener los elementos de una lista se utiliza el operador $.
4. Podemos acceder a un elemento por los índices.

In [4]:
message("Creando lista:")
mi_lista <- list(hombre = "Pedro", mujer = "Maria",casados = TRUE, num.hijos = 3, edad.hijos = c(4,7,9))
mi_lista

message("Accediendo a los elementos con el operador $:")
mi_lista$hombre
mi_lista$casados

message("Accediendo a los elementos con los índices:")
mi_lista[[5]]

Creando lista:


$hombre
[1] "Pedro"

$mujer
[1] "Maria"

$casados
[1] TRUE

$num.hijos
[1] 3

$edad.hijos
[1] 4 7 9

Accediendo a los elementos con el operador $:


[1] "Pedro"

[1] TRUE

Accediendo a los elementos con los índices:


[1] 4 7 9

- Explicar las diferencias entre las funciones `rbind()`, `cbind()` y `merge()` para combinar dos estructuras de dos dimensiones en $R$. Usa ejemplos para demostrar esas diferencias.

**rbind()**

Toma una secuencia de vectores, matrices o data frames y los combina por filas.

In [5]:
message("COMBINANDO VECTORES POR FILA: ");

message("Vector a: ");
a <- 1:3
a

message("Vector b: ");
b <- 4:6
b

message("Matriz resultante: ");
rbind(a,b)



message("COMBINANDO MATRICES POR FILA: ");

message("Matriz A: ");
A <- matrix(
    1:12,
    nrow = 4,
    dimnames = list(
        c("f1", "f2", "f3", "f4"),
        c("c1", "c2", "c3")
    )
)
A

message("Matriz B: ");
B <- matrix(
     seq.int(2, 24, 2),
     nrow = 4,
     dimnames = list(
         c("f5", "f6", "f7", "f8"),
         c("c4", "c5", "c6")
     )
)
B

message("Matriz resultante: ");
rbind(A,B)

COMBINANDO VECTORES POR FILA: 
Vector a: 


[1] 1 2 3

Vector b: 


[1] 4 5 6

Matriz resultante: 


[,1] [,2] [,3]
a 1    2    3   
b 4    5    6

COMBINANDO MATRICES POR FILA: 
Matriz A: 


c1 c2 c3
f1 1  5   9
f2 2  6  10
f3 3  7  11
f4 4  8  12

Matriz B: 


c4 c5 c6
f5 2  10 18
f6 4  12 20
f7 6  14 22
f8 8  16 24

Matriz resultante: 


c1 c2 c3
f1 1   5  9
f2 2   6 10
f3 3   7 11
f4 4   8 12
f5 2  10 18
f6 4  12 20
f7 6  14 22
f8 8  16 24

**cbind()**

Toma una secuencia de vectores, matrices o data frames y los combina por columnas.

In [6]:
message("COMBINANDO VECTORES POR COLUMNA: ");

message("Vector Va: ");
Va <- c(1,4)
Va

message("Vector Vb: ");
Vb <- c(2,5)
Vb

message("Vector Vc: ");
Vc <- c(3,6)
Vc

message("Matriz resultante: ");
cbind(Va,Vb,Vc)



message("COMBINANDO MATRICES POR COLUMNA: ");

message("Matriz A: ");
A

message("Matriz B: ");
B

message("Matriz resultante: ");
cbind(A,B)

COMBINANDO VECTORES POR COLUMNA: 
Vector Va: 


[1] 1 4

Vector Vb: 


[1] 2 5

Vector Vc: 


[1] 3 6

Matriz resultante: 


Va Vb Vc
[1,] 1  2  3 
[2,] 4  5  6

COMBINANDO MATRICES POR COLUMNA: 
Matriz A: 


c1 c2 c3
f1 1  5   9
f2 2  6  10
f3 3  7  11
f4 4  8  12

Matriz B: 


c4 c5 c6
f5 2  10 18
f6 4  12 20
f7 6  14 22
f8 8  16 24

Matriz resultante: 


c1 c2 c3 c4 c5 c6
f1 1  5   9 2  10 18
f2 2  6  10 4  12 20
f3 3  7  11 6  14 22
f4 4  8  12 8  16 24

**merge()**

Combina dos data frames por las columnas comunes. Se debe especificar qué columnas contienen los valores comunes de los data frames. Por defecto, la función `merge()` utiliza todas las columnas comunes de los dos data frames.

In [7]:
message("Data frame df1:")
df1 <- data.frame(
                nombre = c("Alberto", "Ivonne","Yeny","Alejandro","Sofia") ,
                edad = c(61,27,56,35,43),
                casado = c(TRUE,FALSE,T,F,F)
)
df1

message("Data frame df2:")
df2 <- data.frame(
  nombre = c("Alejandro","Leonardo","Sofia","Lucia","Felix"),
  sexo = c('M','M','F','F','M'),
  talla = c(1.60,1.50,1.53,1.63,1.55)
)
df2

message("Merge de df1 y df2:")
merge(df1,df2,by="nombre")

message("Merge de df1 y df2 con todos los elementos:")
merge(df1,df2,by="nombre",all = TRUE)

Data frame df1:


nombre    edad casado
1 Alberto   61    TRUE 
2 Ivonne    27   FALSE 
3 Yeny      56    TRUE 
4 Alejandro 35   FALSE 
5 Sofia     43   FALSE

Data frame df2:


nombre    sexo talla
1 Alejandro M    1.60 
2 Leonardo  M    1.50 
3 Sofia     F    1.53 
4 Lucia     F    1.63 
5 Felix     M    1.55

Merge de df1 y df2:


nombre    edad casado sexo talla
1 Alejandro 35   FALSE  M    1.60 
2 Sofia     43   FALSE  F    1.53

Merge de df1 y df2 con todos los elementos:


nombre    edad casado sexo talla
1 Alberto   61    TRUE  NA     NA 
2 Alejandro 35   FALSE  M    1.60 
3 Ivonne    27   FALSE  NA     NA 
4 Sofia     43   FALSE  F    1.53 
5 Yeny      56    TRUE  NA     NA 
6 Felix     NA      NA  M    1.55 
7 Leonardo  NA      NA  M    1.50 
8 Lucia     NA      NA  F    1.63

3.

(a)  Construye  y almacena una matriz $4 \times 2$ que se completa  por  fila con los valores $4.3, 3.1, 8.2, 8.2, 3.2, 0.9, 1.6$ y $6.5$, en ese orden.

In [8]:
x <- c(4.3, 3.1, 8.2, 8.2, 3.2, 0.9, 1.6, 6.5)
mimatrix <- matrix(x, nrow = 4, byrow = TRUE)
mimatrix

[,1] [,2]
[1,] 4.3  3.1 
[2,] 8.2  8.2 
[3,] 3.2  0.9 
[4,] 1.6  6.5

(b) Confirma que las dimensiones de la matriz de (a) son $3 \times  2$ si se elimina una fila.

In [9]:
#Dimension de la matriz luego de eliminar una fila
dim(mimatrix[-1,])

[1] 3 2

(c) Sobrescribe la segunda columna de la matriz de (a) con esa misma columna ordenada de menor a mayor.

In [10]:
message("Matriz de (a): ")
mimatrix

message("Sobrescribiendo la matriz de (a): ")
mimatrix[,2] <- sort(mimatrix[,2])
mimatrix

Matriz de (a): 


[,1] [,2]
[1,] 4.3  3.1 
[2,] 8.2  8.2 
[3,] 3.2  0.9 
[4,] 1.6  6.5

Sobrescribiendo la matriz de (a): 


[,1] [,2]
[1,] 4.3  0.9 
[2,] 8.2  3.1 
[3,] 3.2  6.5 
[4,] 1.6  8.2

(d) ¿Qué devuelve R si se elimina la cuarta fila y la primera columna de (c)?. Utiliza `matrix` para asegurar que el resultado sea una matriz de una sola columna, en lugar de un vector.

In [11]:
message("Eliminando la cuarta fila y la primera columna de (c):")
elimatrix <- mimatrix[-4,-1]
elimatrix
message("El resultado es vector: ",is.vector(elimatrix))
message("El resultado es matriz: ",is.matrix(elimatrix))

Eliminando la cuarta fila y la primera columna de (c):


[1] 0.9 3.1 6.5

El resultado es vector: TRUE
El resultado es matriz: FALSE


In [12]:
message("Asegurando que el resultado sea matrix:")
elimatrix2 <- matrix(mimatrix[-4,-1])
elimatrix2
message("El resultado es vector: ",is.vector(elimatrix2))
message("El resultado es matriz: ",is.matrix(elimatrix2))

Asegurando que el resultado sea matrix:


[,1]
[1,] 0.9 
[2,] 3.1 
[3,] 6.5

El resultado es vector: FALSE
El resultado es matriz: TRUE


(e) Guarde los cuatro elementos inferiores de (c) como una nueva matriz $2\times 2$.

In [13]:
newmatrix <- mimatrix[3:4,1:2]
newmatrix
message("Dimension de la matriz resultante: ")
dim(newmatrix)

[,1] [,2]
[1,] 3.2  6.5 
[2,] 1.6  8.2

Dimension de la matriz resultante: 


[1] 2 2

(f) Sobrescribe en este orden los elementos de (c) en las posiciones $(4, 2), (1, 2), (4, 1)$ y $(1, 1)$ con $\frac{1}{2}$ de los dos valores de la diagonal de (e).

In [14]:
mimatrix[rep(c(4,1),2),rep(c(2,1),each=2)] <- 1/2*diag(newmatrix)
mimatrix

[,1] [,2]
[1,] 4.1  4.1 
[2,] 8.2  3.1 
[3,] 3.2  6.5 
[4,] 1.6  1.6

4.Calcula lo siguiente:

$$
\dfrac{2}{7}\begin{bmatrix}
        1 & 2  \\[0.3em]
        2 &  4 \\[0.3em]
        7 & 6 
     \end{bmatrix} - \begin{bmatrix}
        10 & 20  \\[0.3em]
        30 &  40 \\[0.3em]
        50 & 60 
\end{bmatrix}
$$

In [15]:
message("Matriz A:")
A <- matrix(c(1,2,2,4,7,6),nrow = 3, byrow = TRUE)
A

message("Matriz B:")
B <- matrix(10*1:6,nrow = 3, byrow = TRUE)
B

a <- 2/7

message("Matriz resultante despues de realizar el cálculo: ")
a*A - B

Matriz A:


[,1] [,2]
[1,] 1    2   
[2,] 2    4   
[3,] 7    6

Matriz B:


[,1] [,2]
[1,] 10   20  
[2,] 30   40  
[3,] 50   60

Matriz resultante despues de realizar el cálculo: 


[,1]       [,2]     
[1,]  -9.714286 -19.42857
[2,] -29.428571 -38.85714
[3,] -48.000000 -58.28571

5.Almacena estas dos matrices:
$$
A = \begin{bmatrix}
1 \\[0.3em]
2 \\[0.3em]
7 
\end{bmatrix}\qquad B = \begin{bmatrix}
3 \\[0.3em]
4 \\[0.3em]
8 
\end{bmatrix}
$$

In [16]:
message("Matriz A")
message("Dimension de A, mxn, es: ",dim(A)[1],"x",dim(A)[2])
A <- matrix(c(1,2,7))
A

message("Matriz B")
message("Dimension de B, pxq, es: ",dim(B)[1],"x",dim(B)[2])
B <- matrix(c(3,4,8))
B

Matriz A
Dimension de A, mxn, es: 3x2


[,1]
[1,] 1   
[2,] 2   
[3,] 7

Matriz B
Dimension de B, pxq, es: 3x2


[,1]
[1,] 3   
[2,] 4   
[3,] 8

¿Cuál de las siguientes multiplicaciones son posibles?. Para los que son, calcula el resultado.

- $A \cdot B$

No es posible ya que `n!=p`.

- $A^T \cdot B$

In [17]:
#Si es posible, ya que m==p
t(A)%*%B

[,1]
[1,] 67

- $B^T \cdot (A \cdot A^T)$

In [18]:
#Si es posible
t(B)%*%(A%*%t(A))

[,1] [,2] [,3]
[1,] 67   134  469

- $[(B\cdot B^T) + (A \cdot A^T)- 100I_3 ]^{-1}$

In [19]:
#Si es posible
solve( B%*%t(B) + A%*%t(A) - 100*diag(x=3) ) 

[,1]         [,2]         [,3]       
[1,] -0.007923676  0.003123274 0.007843334
[2,]  0.003123274 -0.005350239 0.011483806
[3,]  0.007843334  0.011483806 0.017584735

6.La función `diag` tiene varios usos, uno de los cuales es tomar un vector como  entrada y crea una matriz cuadrada con ese vector en la diagonal. Crea una matriz  $21 \times 21$ con la secuencia de $10$ a $0$ y a $10$ (es decir, $10, 9, \dots, 1, 0, 1, \dots, 10$).

In [20]:
diag(x = c(10:0,1:10), nrow = 21)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 10   0    0    0    0    0    0    0    0    0     ⋯     0     0    
 [2,]  0   9    0    0    0    0    0    0    0    0     ⋯     0     0    
 [3,]  0   0    8    0    0    0    0    0    0    0     ⋯     0     0    
 [4,]  0   0    0    7    0    0    0    0    0    0     ⋯     0     0    
 [5,]  0   0    0    0    6    0    0    0    0    0     ⋯     0     0    
 [6,]  0   0    0    0    0    5    0    0    0    0     ⋯     0     0    
 [7,]  0   0    0    0    0    0    4    0    0    0     ⋯     0     0    
 [8,]  0   0    0    0    0    0    0    3    0    0     ⋯     0     0    
 [9,]  0   0    0    0    0    0    0    0    2    0     ⋯     0     0    
[10,]  0   0    0    0    0    0    0    0    0    1     ⋯     0     0    
[11,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[12,]  0   0    0    0    0    0    0    0    0    0     ⋯     1     0    
[13,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     2    
[14,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[15,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[16,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[17,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[18,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[19,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[20,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[21,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
      [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21]
 [1,] 0     0     0     0     0     0     0      0   
 [2,] 0     0     0     0     0     0     0      0   
 [3,] 0     0     0     0     0     0     0      0   
 [4,] 0     0     0     0     0     0     0      0   
 [5,] 0     0     0     0     0     0     0      0   
 [6,] 0     0     0     0     0     0     0      0   
 [7,] 0     0     0     0     0     0     0      0   
 [8,] 0     0     0     0     0     0     0      0   
 [9,] 0     0     0     0     0     0     0      0   
[10,] 0     0     0     0     0     0     0      0   
[11,] 0     0     0     0     0     0     0      0   
[12,] 0     0     0     0     0     0     0      0   
[13,] 0     0     0     0     0     0     0      0   
[14,] 3     0     0     0     0     0     0      0   
[15,] 0     4     0     0     0     0     0      0   
[16,] 0     0     5     0     0     0     0      0   
[17,] 0     0     0     6     0     0     0      0   
[18,] 0     0     0     0     7     0     0      0   
[19,] 0     0     0     0     0     8     0      0   
[20,] 0     0     0     0     0     0     9      0   
[21,] 0     0     0     0     0     0     0     10

7.Para
$$
A = \begin{bmatrix}
        2 & 0 & 0  & 0    \\[0.3em]
        0 & 3 & 0 & 0     \\[0.3em]
        0 & 0 & 5 & 0      \\[0.3em]
        0 & 0 & 0 & -1           
\end{bmatrix}
$$

Comprueba que $A^{-1}\cdot A -I_4$ proporciona una matriz $4 \times 4$ de ceros.

In [21]:
message("Matriz A")
A <- diag(x = c(2,3,5,-1),nrow = 4)
A
message("Matriz I4")
I4 <- diag(x = 4)
I4

message("Matriz resultante después de realizar el cálculo: ")
solve(A)%*%A-I4

Matriz A


[,1] [,2] [,3] [,4]
[1,] 2    0    0     0  
[2,] 0    3    0     0  
[3,] 0    0    5     0  
[4,] 0    0    0    -1

Matriz I4


[,1] [,2] [,3] [,4]
[1,] 1    0    0    0   
[2,] 0    1    0    0   
[3,] 0    0    1    0   
[4,] 0    0    0    1

Matriz resultante después de realizar el cálculo: 


[,1] [,2] [,3] [,4]
[1,] 0    0    0    0   
[2,] 0    0    0    0   
[3,] 0    0    0    0   
[4,] 0    0    0    0

8.Usa las funciones `matrix()`, `seq()` y `rep()` para construir la matrices de Hankel $5 \times 5$.
$$
M = \begin{bmatrix}
        1 & 2 & 3  & 4 & 5         \\[0.3em]
        2 & 3 & 4 & 5 & 6           \\[0.3em]
        3 & 4 & 5 & 6 & 7           \\[0.3em]
       4 & 5 & 6 & 7 & 8           \\[0.3em]
        5 & 6 & 7 & 8 & 9           
\end{bmatrix}
$$

In [22]:
M <- matrix(rep(1:5,5)+rep(0:4,each=5),ncol=5)
M

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4    5   
[2,] 2    3    4    5    6   
[3,] 3    4    5    6    7   
[4,] 4    5    6    7    8   
[5,] 5    6    7    8    9

Convierte el código en una función  que puede ser usado para construir matrices de dimensión $n \times n$.

In [23]:
FunMHankel <- function(x)
{
  n = (length(x)+1)/2 # length = 2*n-1
  matrix( x[rep(seq(1:n),n) + rep(seq(0,n-1), each = n )], ncol = n )
}

Usa esa función para mostrar las salida de Matrices de Hankel de orden $10 \times 10$ y $12 \times 12$.

In [24]:
#n = 5
#cant. elementos: 9 = 2*5-1
N5 <- 1:9 

#n=10
#cant. elementos: 19 = 2*10-1
N10 <- c(8,15,13,27,18,53,45,71,84,92,7,26,32,77,55,33,51,29,89) 

#n=12
#cant. elementos: 23 = 2*12-1
N12 <- c(4,29,30,44,10,42,47,32,14,23,31,46,19,28,34,36,8,21,15,49,45,16,41) 

message("Hankel 5x5")
FunMHankel(N5) 

message("Hankel 10x10")
FunMHankel(N10)

message("Hankel 12x12")
FunMHankel(N12)

Hankel 5x5


[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4    5   
[2,] 2    3    4    5    6   
[3,] 3    4    5    6    7   
[4,] 4    5    6    7    8   
[5,] 5    6    7    8    9

Hankel 10x10


[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]  8   15   13   27   18   53   45   71   84   92   
 [2,] 15   13   27   18   53   45   71   84   92    7   
 [3,] 13   27   18   53   45   71   84   92    7   26   
 [4,] 27   18   53   45   71   84   92    7   26   32   
 [5,] 18   53   45   71   84   92    7   26   32   77   
 [6,] 53   45   71   84   92    7   26   32   77   55   
 [7,] 45   71   84   92    7   26   32   77   55   33   
 [8,] 71   84   92    7   26   32   77   55   33   51   
 [9,] 84   92    7   26   32   77   55   33   51   29   
[10,] 92    7   26   32   77   55   33   51   29   89

Hankel 12x12


[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12]
 [1,]  4   29   30   44   10   42   47   32   14   23    31    46   
 [2,] 29   30   44   10   42   47   32   14   23   31    46    19   
 [3,] 30   44   10   42   47   32   14   23   31   46    19    28   
 [4,] 44   10   42   47   32   14   23   31   46   19    28    34   
 [5,] 10   42   47   32   14   23   31   46   19   28    34    36   
 [6,] 42   47   32   14   23   31   46   19   28   34    36     8   
 [7,] 47   32   14   23   31   46   19   28   34   36     8    21   
 [8,] 32   14   23   31   46   19   28   34   36    8    21    15   
 [9,] 14   23   31   46   19   28   34   36    8   21    15    49   
[10,] 23   31   46   19   28   34   36    8   21   15    49    45   
[11,] 31   46   19   28   34   36    8   21   15   49    45    16   
[12,] 46   19   28   34   36    8   21   15   49   45    16    41

9.La matriz de Hilbert $n \times n$ tiene a los elementos $(i,j)$ dados por $1/(i + j-1)$.

- Escribe una función que muestra una matriz de Hilbert $n \times n$ como salida para entero positivo $n$.

In [25]:
FunMHilbert <- function(n)
{
  matrix(1/(rep(1:n,each = n) + 1:n - 1),nrow = n, byrow = TRUE)
}

message("Hilbert 3x3:")
Hilbert3 <- FunMHilbert(3)
Hilbert3

message("Hilbert 10x10:")
Hilbert10 <- FunMHilbert(10)
Hilbert10

Hilbert 3x3:


[,1]      [,2]      [,3]     
[1,] 1.0000000 0.5000000 0.3333333
[2,] 0.5000000 0.3333333 0.2500000
[3,] 0.3333333 0.2500000 0.2000000

Hilbert 10x10:


[,1]      [,2]       [,3]       [,4]       [,5]       [,6]      
 [1,] 1.0000000 0.50000000 0.33333333 0.25000000 0.20000000 0.16666667
 [2,] 0.5000000 0.33333333 0.25000000 0.20000000 0.16666667 0.14285714
 [3,] 0.3333333 0.25000000 0.20000000 0.16666667 0.14285714 0.12500000
 [4,] 0.2500000 0.20000000 0.16666667 0.14285714 0.12500000 0.11111111
 [5,] 0.2000000 0.16666667 0.14285714 0.12500000 0.11111111 0.10000000
 [6,] 0.1666667 0.14285714 0.12500000 0.11111111 0.10000000 0.09090909
 [7,] 0.1428571 0.12500000 0.11111111 0.10000000 0.09090909 0.08333333
 [8,] 0.1250000 0.11111111 0.10000000 0.09090909 0.08333333 0.07692308
 [9,] 0.1111111 0.10000000 0.09090909 0.08333333 0.07692308 0.07142857
[10,] 0.1000000 0.09090909 0.08333333 0.07692308 0.07142857 0.06666667
      [,7]       [,8]       [,9]       [,10]     
 [1,] 0.14285714 0.12500000 0.11111111 0.10000000
 [2,] 0.12500000 0.11111111 0.10000000 0.09090909
 [3,] 0.11111111 0.10000000 0.09090909 0.08333333
 [4,] 0.10000000 0.09090909 0.08333333 0.07692308
 [5,] 0.09090909 0.08333333 0.07692308 0.07142857
 [6,] 0.08333333 0.07692308 0.07142857 0.06666667
 [7,] 0.07692308 0.07142857 0.06666667 0.06250000
 [8,] 0.07142857 0.06666667 0.06250000 0.05882353
 [9,] 0.06666667 0.06250000 0.05882353 0.05555556
[10,] 0.06250000 0.05882353 0.05555556 0.05263158

- ¿Son todas las matrices de Hilbert invertibles?

Sí. Además, su inversa puede ser expresada usando *coeficientes binomiales* y todas sus entradas son números enteros.

- Usa `solve()` y `qr.solve()` para calcular la inversa de las matrices Hilbert, por ejemplo, cuando $n = 10$. 

In [26]:
message("Hallando la inversa de Hilbert 10x10 usando solve():")
solve(Hilbert10)

message("Hallando la inversa de Hilbert 10x10 usando qr.solve():")
qr.solve(Hilbert10, tol = 0)

Hallando la inversa de Hilbert 10x10 usando solve():


[,1]          [,2]          [,3]          [,4]          [,5]         
 [1,]  9.999719e+01 -4.949757e+03  7.919482e+04 -6.005529e+05       2522295
 [2,] -4.949756e+03  3.266790e+05 -5.880152e+06  4.756344e+07    -208088462
 [3,]  7.919480e+04 -5.880151e+06  1.128980e+08 -9.512635e+08    4280662450
 [4,] -6.005527e+05  4.756343e+07 -9.512634e+08  8.244246e+09  -37871868827
 [5,]  2.522294e+06 -2.080884e+08  4.280662e+09 -3.787187e+10  176734991839
 [6,] -6.305679e+06  5.350810e+08 -1.123668e+10  1.009913e+11 -477183582308
 [7,]  9.608580e+06 -8.323436e+08  1.775667e+10 -1.615857e+11  771204559101
 [8,] -8.750614e+06  7.700557e+08 -1.663323e+10  1.528915e+11 -735791094422
 [9,]  4.375282e+06 -3.898391e+08  8.505604e+09 -7.883452e+10  382044919568
[10,] -9.236661e+05  8.313037e+07 -1.828875e+09  1.706955e+10  -83214282335
      [,6]          [,7]          [,8]          [,9]          [,10]        
 [1,] -6.305682e+06  9.608586e+06 -8.750620e+06  4.375286e+06 -9.236669e+05
 [2,]  5.350812e+08 -8.323439e+08  7.700561e+08 -3.898393e+08  8.313042e+07
 [3,] -1.123669e+10  1.775667e+10 -1.663324e+10  8.505608e+09 -1.828876e+09
 [4,]  1.009913e+11 -1.615857e+11  1.528915e+11 -7.883455e+10  1.706956e+10
 [5,] -4.771836e+11  7.712047e+11 -7.357912e+11  3.820450e+11 -8.321430e+10
 [6,]  1.301409e+12 -2.120813e+12  2.037577e+12 -1.064270e+12  2.330005e+11
 [7,] -2.120813e+12  3.480308e+12 -3.363622e+12  1.765901e+12 -3.883348e+11
 [8,]  2.037577e+12 -3.363622e+12  3.267520e+12 -1.723107e+12  3.804102e+11
 [9,] -1.064270e+12  1.765901e+12 -1.723107e+12  9.122340e+11 -2.020931e+11
[10,]  2.330005e+11 -3.883348e+11  3.804101e+11 -2.020931e+11  4.490964e+10

Hallando la inversa de Hilbert 10x10 usando qr.solve():


[,1]          [,2]          [,3]          [,4]          [,5]         
 [1,]  9.999763e+01 -4.949796e+03  7.919566e+04 -6.005606e+05       2522332
 [2,] -4.949794e+03  3.266822e+05 -5.880222e+06  4.756409e+07    -208091541
 [3,]  7.919557e+04 -5.880218e+06  1.128994e+08 -9.512768e+08    4280726081
 [4,] -6.005595e+05  4.756403e+07 -9.512762e+08  8.244364e+09  -37872432943
 [5,]  2.522326e+06 -2.080912e+08  4.280722e+09 -3.787241e+10  176737626224
 [6,] -6.305764e+06  5.350885e+08 -1.123685e+10  1.009928e+11 -477190694526
 [7,]  9.608718e+06 -8.323557e+08  1.775693e+10 -1.615881e+11  771216047252
 [8,] -8.750745e+06  7.700672e+08 -1.663348e+10  1.528938e+11 -735802046037
 [9,]  4.375350e+06 -3.898451e+08  8.505733e+09 -7.883571e+10  382050600435
[10,] -9.236809e+05  8.313167e+07 -1.828903e+09  1.706981e+10  -83215518397
      [,6]          [,7]          [,8]          [,9]          [,10]        
 [1,] -6.305784e+06  9.608755e+06 -8.750784e+06  4.375372e+06 -9.236858e+05
 [2,]  5.350897e+08 -8.323580e+08  7.700697e+08 -3.898465e+08  8.313200e+07
 [3,] -1.123686e+10  1.775696e+10 -1.663352e+10  8.505756e+09 -1.828909e+09
 [4,]  1.009929e+11 -1.615883e+11  1.528940e+11 -7.883586e+10  1.706985e+10
 [5,] -4.771909e+11  7.712167e+11 -7.358029e+11  3.820511e+11 -8.321566e+10
 [6,]  1.301428e+12 -2.120845e+12  2.037609e+12 -1.064286e+12  2.330042e+11
 [7,] -2.120844e+12  3.480361e+12 -3.363673e+12  1.765928e+12 -3.883407e+11
 [8,]  2.037607e+12 -3.363671e+12  3.267568e+12 -1.723133e+12  3.804158e+11
 [9,] -1.064285e+12  1.765927e+12 -1.723132e+12  9.122472e+11 -2.020961e+11
[10,]  2.330039e+11 -3.883404e+11  3.804156e+11 -2.020960e+11  4.491027e+10

10.

- Genere un array tridimensional con dimensiones $4 \times 3 \times 2$ que contengan los números del $1$ al $24$.

In [27]:
a <- array(1:24, dim = c(4,3,2))
a

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24

- Extraiga la última porción `(a[,, 2])` del array y guárdela como una matriz $M$.

In [28]:
M <- a[,,2]
M

message("El resultado es matriz: ",is.matrix(M))

[,1] [,2] [,3]
[1,] 13   17   21  
[2,] 14   18   22  
[3,] 15   19   23  
[4,] 16   20   24

El resultado es matriz: TRUE


- Genera un nuevo array de dimensiones $4 \times 3 \times 3$ que es idéntica a la matriz anterior, pero añade la matriz $M$ como la tercera entrada en la tercera dimensión.

In [29]:
b <- array(c(a,M), dim = c(4,3,3))
b

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24

, , 3

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24

11.Crea una matriz aleatoria entera $6 \times 10$ escogidos entre $1,2,\dots, 10$, ejecutando las siguientes líneas de código.

In [30]:
set.seed(75)
aMat <- matrix( sample(10, size=60, replace=T), nr=6)
aMat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 3     6   7    7     2    4    3   7     1   4    
[2,] 1     9   8    7     2    6   10   9     5   2    
[3,] 7    10   8    4    10    5    4   8     4   4    
[4,] 4     3   1    1     3    3    9   7     4   2    
[5,] 1     8   1    9     9    8    1   3     7   7    
[6,] 2     6   7    5     6   10    4   6    10   1

(a) Encuentra el número de entradas en cada fila que son mayores que $4$.

In [31]:
apply(aMat,1,function(x){sum(x>4)}) #trabajamos sobre las filas

[1] 4 7 6 2 6 7

(b) ¿Qué filas contienen exactamente dos ocurrencias del número siete?

In [32]:
message("Cantidad de 7s por fila:")
cant7porfila <- apply(aMat,1,function(x){sum(x==7)}) #trabajamos sobre las filas
cant7porfila

message("2 ocurrencias por fila:")
cant7porfila == 2

message("Filas que contienen 2 ocurrencias del número 7:")
which(cant7porfila == 2)

Cantidad de 7s por fila:


[1] 3 1 1 1 2 1

2 ocurrencias por fila:


[1] FALSE FALSE FALSE FALSE  TRUE FALSE

Filas que contienen 2 ocurrencias del número 7:


[1] 5

(c) Encuentra aquellos pares de columnas cuyo total (sobre ambas columnas) es mayor que 75. La respuesta debería ser una matriz con dos columnas; así, por ejemplo, la fila $(1, 2)$ en la matriz de salida significa que la suma de las columnas $1$ y $2$ en la matriz original es mayor que 75. Se permite repetir una columna; por ejemplo, la matriz de salida final podría contener las filas $(1, 2), (2, 1)$ y $(2, 2)$.

In [33]:
message("Suma de los elementos por columna:")
SumxColum <- apply(aMat,2,function(x){sum(x)})
SumxColum

message("Matriz cuyo elemento (i,j) representa la suma de los elementos de las columnas i y j:")
matSumxColum <- matrix(SumxColum + rep(SumxColum, each = length(SumxColum)),ncol= length(SumxColum), byrow = TRUE)
matSumxColum

message("Pares de columnas que cumplen la condición:")
which(matSumxColum > 75, arr.ind = TRUE)

Suma de los elementos por columna:


[1] 18 42 32 33 32 36 31 40 31 20

Matriz cuyo elemento (i,j) representa la suma de los elementos de las columnas i y j:


[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,] 36   60   50   51   50   54   49   58   49   38   
 [2,] 60   84   74   75   74   78   73   82   73   62   
 [3,] 50   74   64   65   64   68   63   72   63   52   
 [4,] 51   75   65   66   65   69   64   73   64   53   
 [5,] 50   74   64   65   64   68   63   72   63   52   
 [6,] 54   78   68   69   68   72   67   76   67   56   
 [7,] 49   73   63   64   63   67   62   71   62   51   
 [8,] 58   82   72   73   72   76   71   80   71   60   
 [9,] 49   73   63   64   63   67   62   71   62   51   
[10,] 38   62   52   53   52   56   51   60   51   40

Pares de columnas que cumplen la condición:


row col
[1,] 2   2  
[2,] 6   2  
[3,] 8   2  
[4,] 2   6  
[5,] 8   6  
[6,] 2   8  
[7,] 6   8  
[8,] 8   8

¿Qué sucede si no se permiten repeticiones? Entonces, solo se permitiría $(1, 2)$ de $(1, 2), (2, 1)$ y $(2, 2)$?


In [34]:
message("Consideramos solo los elementos que esten sobre la diagonal principal:")
matSumxColum[lower.tri(matSumxColum,diag = TRUE)] <- 0
matSumxColum

message("Pares de columnas que cumplen la condición:")
which(matSumxColum > 75, arr.ind = TRUE)

Consideramos solo los elementos que esten sobre la diagonal principal:


[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,] 0    60   50   51   50   54   49   58   49   38   
 [2,] 0     0   74   75   74   78   73   82   73   62   
 [3,] 0     0    0   65   64   68   63   72   63   52   
 [4,] 0     0    0    0   65   69   64   73   64   53   
 [5,] 0     0    0    0    0   68   63   72   63   52   
 [6,] 0     0    0    0    0    0   67   76   67   56   
 [7,] 0     0    0    0    0    0    0   71   62   51   
 [8,] 0     0    0    0    0    0    0    0   71   60   
 [9,] 0     0    0    0    0    0    0    0    0   51   
[10,] 0     0    0    0    0    0    0    0    0    0

Pares de columnas que cumplen la condición:


row col
[1,] 2   6  
[2,] 2   8  
[3,] 6   8